[package]
name = "clmm_pool"
edition = "2024"

[addresses]
clmm_pool = "0x0"

[dev-dependencies]

[dev-addresses]

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "ad937889f2f99bc666b05aaeadccb0d3d7d1f863"
override = true

[dependencies.move_stl]
git = "https://github.com/luck-28/MAGMA-move-stl.git"
rev = "main"

[dependencies.integer_mate]
git = "https://github.com/luck-28/MAGMA-integer-mate.git"
rev = "main"

[dependencies.gauge_cap]
local = "../gauge_cap"

[dependencies.price_provider]
local = "../price_provider"
